name: "static analysis"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform: [ ~1.7 ]
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}

      - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: make
