name: "terraform tests"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.7"

      - name: terraform init (install modules/providers)
        run: terraform init -backend=false -upgrade -no-color

      - name: terraform test
        run: terraform test -no-color
